config/routes.rb
Emberjsapp::Application.routes.draw do
  resources :samples
   root :to => 'samples#index'
   match "update_pic" , :controller=> "samples", :action=>"update_pic"

end

app/models/sample.rb
class Sample < ActiveRecord::Base
  attr_accessible :pic_name, :pic, :left ,:top,:picname
  mount_uploader :pic, PicUploader
  validates :pic, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/samples_controller.rb
require 'base64'
class SamplesController < ApplicationController
#respond_to :json
  # GET /samples
  # GET /samples.json
  def index
	
#	respond_with Sample.all
    @samples = Sample.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @samples }
    end
  end


def update_pic
     
    @sample = Sample.find(params[:id])
   data = params[:data_url]

image_data = Base64.decode64(data['data:image/jpg;base64,'.length .. -1])

File.open("#{Rails.root}/public/#{@sample.pic}", 'wb') do |f|
  f.write image_data
end

end
  # GET /samples/1
  # GET /samples/1.json
  def show
	
#	 respond_with Sample.find(params[:id])
    @sample = Sample.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/new
  # GET /samples/new.json
  def new
    @sample = Sample.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/1/edit
  def edit
    @sample = Sample.find(params[:id])
  end

  # POST /samples
  # POST /samples.json
  def create
    params[:sample][:left]=0
    params[:sample][:top]=0
    @sample = Sample.new(params[:sample])
#    @sample.left=0
#    @sample.top=0
    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Image is successfully Uploaded.' }
        format.json { render json: @sample, status: :created, location: @sample }
      else
        format.html { render action: "new" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /samples/1
  # PUT /samples/1.json
  def update
    @sample = Sample.find(params[:id])

    respond_to do |format|
      if @sample.update_attributes(params[:sample])
        format.html { redirect_to @sample, notice: 'Image is successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy

    respond_to do |format|
      format.html { redirect_to samples_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test Task</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<%= yield :head %>
</head>
<body>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/samples/_form.html.erb
<div>
<%= simple_form_for @sample ,:html => { class: 'form-horizontal',:multipart => true} do |f| %>

  <%= f.error_notification %>
<fieldset >    
	 <legend>Upload Image</legend>

  <div class="form-inputs">
    <%= f.input :picname %>
    
    <%= f.input :pic %>

  </div>

  </fieldset>

  <div class="form-actions">
    <%= f.submit  "Upload",:class=>"btn"%>
    <%= link_to 'Back', samples_path ,:class=>"btn "%>
  </div>
<% end %>

</div>

app/views/samples/edit.html.erb
<h1>Edit Image</h1>

<%= render 'form' %>

app/views/samples/index.html.erb
<div >
<h1 style="padding-left:250px">List of Uploaded Images</h1>
<%= link_to 'Upload Image', new_sample_path ,:class=>"btn" %>
<br/></br>
<table id="users-table" class="table">
<tr>
    <th>Pic Name</th>
    <th>Picture</th>
    <th></th>
    <th></th>

<% @samples.each do |sample| %>
  <tr>
    <td><%= sample.picname %></td>
    <td> <%= image_tag sample.pic_url ,:style=>"width:100px;height:100px"%></td>
    <td><%= link_to 'Show', sample, :class=>"btn btn-primary btn-small"%></td>
    <td><%= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger btn-small" %></td>
  </tr>
<% end %>


</table>

app/views/samples/new.html.erb
<%= render 'form' %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>
</br>
<div class="container">

<div id="main"><input value="" class="test" type="text" size="2" style="min-width:10px;" /></div>
</br>
     <%= link_to 'Back', samples_path ,:class=>"btn "%>

<!--button id="getimg">get img</button> -->
<%#= image_tag @sample.pic_url ,:style=>"width:450px;height:370px",:id=>"target"%>
<div id="clip"></div>
</div>

<script type='text/javascript'>//<![CDATA[ 
$(window).load(function(){
function resizeInput() {
    $(this).attr('size', $(this).val().length);
    //alert($(this).val().length);
}

$('.test').keyup(resizeInput).each(resizeInput);
});//]]>  

</script>
<script>
$(document).ready(function(){
x_axis=0;
y_axis=0;
$('input').hide();
				
$('#main').click(function( event ) {
if(y_axis===event.pageY && x_axis===event.pageX)
{
$('input').show();
$('input').val("");
$('input').focus();
$('input').css({"position":"absolute","top":event.pageY,"left":event.pageX});
}
});

$('input').blur(function(){
$('input').hide();
var y=$('input').css("top");
var x=$('input').css("left");
$('#main').append("<p id='p"+x+"'></p>");
$('p#p'+x).css({"position":"absolute","top":y,"left":x});
$('p#p'+x).text($('input').val());
//run();
});

$('#main').mousedown(function(event){
	y_axis=event.pageY;
	x_axis=event.pageX;
	run();
	});
$('#main').mouseup(function(event){
var x=event.pageX;
var y=event.pageY;
var temp;
if(x_axis>x)
{
temp=x;
x=x_axis;
x_axis=temp;
}
if(y_axis>y)
{
temp=y;
y=y_axis;
y_axis=temp;
}
if(y_axis!==y && x_axis!==x)
{
	$('#main').append("<div id='div"+x_axis+"'></div>");
	$('div#div'+x_axis).css({"position":"absolute","top":y_axis,"left":x_axis,"border":"1px solid black","width":(x-x_axis),"height":(y-y_axis)});
}
var txt_len =$(".test").length
//alert(txt_len);

if (txt_len > 1)
	run();
});
$('#main').mouseleave(function(e){

			e.preventDefault();	
          	$('canvas').attr("id","canvas1");
          	
            	var can = document.getElementById('canvas1');
            	//alert(can.toDataURL());
            	var dataURL = can.toDataURL();
		$.ajax({
		
			type: "POST",
			url:'/update_pic',
			data: { id:<%=@sample.id%> ,data_url:dataURL },
			dataType: 'html',
				success: function(data) {
					},
				error: function(data) {
					}
		});			            
		        $("canvas").remove(); 
		        
		           
});
});
function run(){
$("input").hide();
	html2canvas(document.getElementById("main"), {
            onrendered: function(canvas) {
            $("canvas").remove(); 
            document.getElementById("clip").appendChild(canvas);
            $('canvas').hide();
            }
            });
}
</script>




<script>
$(function(){

$("#main").css("background-image","url(<%=@sample.pic_url%>)");

});

</script>
<style>
body
{
min-width:100%;
height:700px;
position:relative;
}
#main
{
	xborder:1px solid black;
	width:500px;
	height:370px;
	xbackground-image: url(<%=@sample.pic_url%>);
}
input
{
border:0px;
}

</style>